version: '3'

vars:
  DOCKER_COMPOSE:
    sh: |
      if command -v docker-compose >/dev/null 2>&1; then
        echo docker-compose
      else
        echo "docker compose"
      fi

tasks:
  setup-env:
    desc: "Создать .env из .env.example, если его нет"
    cmds:
      - '[ -f .env ] || cp .env.example .env'
    silent: true

  build:
    desc: "Собрать Docker-образ приложения"
    cmds:
      - task: setup-env
      - docker build -t qa_service .

  up:
    desc: "Собрать и поднять контейнеры (app + db)"
    cmds:
      - task: setup-env
      - "{{.DOCKER_COMPOSE}} up --build"

  down:
    desc: "Остановить и удалить контейнеры"
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  test:
    desc: "Запустить Go-тесты"
    cmds:
      - task: setup-env
      - go test ./... -v

  migrate:
    desc: "Применить ВСЕ миграции через goose"
    cmds:
      - task: setup-env
      - "{{.DOCKER_COMPOSE}} exec app bash -c \"GOOSE_DRIVER=postgres GOOSE_DBSTRING='host=db user=postgres password=pass dbname=qa sslmode=disable' GOOSE_MIGRATION_DIR=/app/migrations goose up\""
